//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceNowTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceNowTest.Properties.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC.
        /// </summary>
        internal static string BranchCode {
            get {
                return ResourceManager.GetString("BranchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BranchName.
        /// </summary>
        internal static string BranchName {
            get {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email@test.com.
        /// </summary>
        internal static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notapwd.
        /// </summary>
        internal static string NonRegisteredPwd {
            get {
                return ResourceManager.GetString("NonRegisteredPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notauser.
        /// </summary>
        internal static string NonRegisteredUser {
            get {
                return ResourceManager.GetString("NonRegisteredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8080.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        internal static string Pwd1 {
            get {
                return ResourceManager.GetString("Pwd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 127.0.0.1.
        /// </summary>
        internal static string ServerUrl {
            get {
                return ResourceManager.GetString("ServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaffName.
        /// </summary>
        internal static string StaffName {
            get {
                return ResourceManager.GetString("StaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        internal static string User1 {
            get {
                return ResourceManager.GetString("User1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email@.
        /// </summary>
        internal static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
    }
}
